-- Disposable, isolated fixtures. No real payments or persistent plan changes.
begin;
create or replace function pg_temp.must_fail(statement text) returns void language plpgsql as $$
declare failed boolean:=false;begin begin execute statement;exception when others then failed:=true;end;if not failed then raise exception 'SECURITY TEST FAILED: %',statement;end if;end $$;
do $$
declare owner_a uuid:=gen_random_uuid();owner_b uuid:=gen_random_uuid();employee uuid:=gen_random_uuid();
 c uuid;c_b uuid;customer uuid;e uuid;p uuid;invoice uuid;token text;trial_end timestamptz;n integer;idx integer;review jsonb;
begin
 insert into auth.users(id,email,email_confirmed_at)values(owner_a,owner_a||'@qa.contractoros.test',now()),(owner_b,owner_b||'@qa.contractoros.test',now()),(employee,employee||'@qa.contractoros.test',now());
 perform set_config('request.jwt.claim.sub',owner_a::text,true);
 insert into public.companies(owner_id,name,owner_name)values(owner_a,'Subscription QA A','QA')returning id into c;
 perform set_config('request.jwt.claim.sub',owner_b::text,true);
 insert into public.companies(owner_id,name,owner_name)values(owner_b,'Subscription QA B','QA')returning id into c_b;
 if public.effective_company_plan(c)<>'free' then raise exception '1 New company must be Free';end if;
 insert into public.customers(company_id,name)values(c,'QA customer')returning id into customer;
 execute 'set local role authenticated';perform set_config('request.jwt.claim.sub',owner_a::text,true);
 for idx in 1..3 loop insert into public.estimates(company_id,customer_id,estimate_number,project_name,valid_until,total,subtotal)values(c,customer,'SUB-QA-'||idx,'QA',current_date+30,100,100)returning id into e;end loop;
 perform pg_temp.must_fail(format('insert into public.estimates(company_id,customer_id,estimate_number,project_name,valid_until,created_at)values(%L,%L,''FOURTH'',''QA'',current_date+30,''2000-01-01'')',c,customer));
 if public.has_company_permission(c,'invoices.create')then raise exception '5,15 Owner Free invoice access';end if;
 perform pg_temp.must_fail(format('update public.company_subscriptions set plan=''business'',status=''active''where company_id=%L',c));
 perform pg_temp.must_fail(format('select public.claim_subscription_customer(%L,''cus_forged'')',c));
 if exists(select 1 from public.company_subscriptions where company_id=c_b)then raise exception '18 Cross-company subscription exposure';end if;
 perform public.start_pro_trial();
 if not public.has_company_permission(c,'invoices.create')then raise exception '10 Trial Pro access';end if;
 perform pg_temp.must_fail('select public.start_pro_trial()');
 token:=public.create_team_invitation(c,'seat2@qa.contractoros.test','admin');
 perform public.create_team_invitation(c,'seat3@qa.contractoros.test','admin');
 perform pg_temp.must_fail(format('select public.create_team_invitation(%L,''seat4@qa.contractoros.test'',''admin'')',c));
 -- Owner can revoke a reserved seat; expired invitations are not counted.
 perform public.revoke_team_invitation((select id from public.team_invitations where company_id=c and email='seat2@qa.contractoros.test'));
 perform public.create_team_invitation(c,'replacement@qa.contractoros.test','admin');
 execute 'reset role';
 update public.company_subscriptions set trial_ends_at=now()-interval '1 second'where company_id=c;
 execute 'set local role authenticated';
 if public.has_company_permission(c,'invoices.create')then raise exception '11 Expired trial retains access';end if;
 perform public.get_subscription_access();
 execute 'reset role';
 update public.company_subscriptions set plan='starter',status='active',current_period_start=now(),current_period_end=now()+interval '30 days' where company_id=c;
 execute 'set local role authenticated';
 insert into public.estimates(company_id,customer_id,estimate_number,project_name,valid_until)values(c,customer,'UNLIMITED','QA',current_date+30);
 if public.has_company_permission(c,'invoices.create')then raise exception 'Starter invoice access';end if;
 execute 'reset role';
 update public.company_subscriptions set plan='pro'where company_id=c;
 update public.estimates set status='approved'where id=e;
 execute 'set local role authenticated';
 p:=public.create_project_from_estimate(e);
 invoice:=public.create_invoice(jsonb_build_object('project_id',p,'invoice_number','SUB-QA-INV','due_date',current_date+30),jsonb_build_array(jsonb_build_object('description','QA','quantity',1,'unit_price',50,'taxable',false)));
 execute 'reset role';
 update public.company_subscriptions set plan='business'where company_id=c;
 update public.team_invitations set revoked_at=now()where company_id=c;
 insert into public.company_members(company_id,user_id,role,status,email)values(c,employee,'employee','active',employee||'@qa.contractoros.test');
 update public.users set company_id=c where id=employee;
 execute 'set local role authenticated';perform set_config('request.jwt.claim.sub',employee::text,true);
 if public.has_company_permission(c,'reports.view')or public.has_company_permission(c,'invoices.view')then raise exception '13,14 Employee on Business finance';end if;
 if exists(select 1 from public.company_subscriptions) then raise exception 'Employee billing exposure';end if;
 perform pg_temp.must_fail('select public.start_pro_trial()');
 perform set_config('request.jwt.claim.sub',owner_a::text,true);
 for idx in 3..10 loop perform public.create_team_invitation(c,'business'||idx||'@qa.contractoros.test','estimator');end loop;
 perform pg_temp.must_fail(format('select public.create_team_invitation(%L,''eleventh@qa.contractoros.test'',''admin'')',c));
 review:=public.request_plan_downgrade('pro');
 if (review->>'seats_to_free')::integer<>7 or not (review->>'provider_confirmation_required')::boolean then raise exception 'Downgrade seat review';end if;
 if (public.get_subscription_access()->>'effective_plan')<>'business' then raise exception 'An unconfirmed downgrade changed access';end if;
 if (select pending_effective_at is not null from public.company_subscriptions where company_id=c)then raise exception 'Unconfirmed downgrade scheduled';end if;
 perform pg_temp.must_fail('select public.request_plan_downgrade(''business'')');
 perform set_config('request.jwt.claim.sub',employee::text,true);
 perform pg_temp.must_fail('select public.request_plan_downgrade(''free'')');
 perform set_config('request.jwt.claim.sub',owner_a::text,true);
 execute 'reset role';
 update public.company_subscriptions set plan='free',status='free'where company_id=c;
 execute 'set local role authenticated';
 if not exists(select 1 from public.invoices where id=invoice)or not exists(select 1 from public.projects where id=p)then raise exception '12 Historical records disappeared';end if;
 perform pg_temp.must_fail(format('select public.send_invoice(%L)',invoice));
 perform pg_temp.must_fail(format('select public.update_project_status(%L,''in_progress'')',p));
 -- Deactivation remains available to resolve over-limit downgrades.
 perform public.set_member_status((select id from public.company_members where company_id=c and user_id=employee),'deactivated');
 execute 'reset role';
 update public.company_subscriptions set plan='pro',status='canceled',current_period_end=now()+interval '1 day'where company_id=c;
 if public.effective_company_plan(c)<>'pro' then raise exception '16 Canceled period access';end if;
 update public.company_subscriptions set current_period_end=now()-interval '1 second'where company_id=c;
 if public.effective_company_plan(c)<>'free' then raise exception '16 Ended period access';end if;
 update public.company_subscriptions set status='past_due',grace_ends_at=now()+interval '7 days'where company_id=c;
 if public.effective_company_plan(c)<>'pro' then raise exception '17 Grace access';end if;
 update public.company_subscriptions set grace_ends_at=now()-interval '1 second'where company_id=c;
 if public.effective_company_plan(c)<>'free' then raise exception '17 Grace expiry';end if;
 if not exists(select 1 from public.subscription_events where company_id=c and event_type='trial_started')or not exists(select 1 from public.subscription_events where company_id=c and event_type='trial_expired')then raise exception 'Trial audit';end if;
 -- Private provider RPC replay and ordering are tested without any real provider transaction.
 perform set_config('request.jwt.claim.sub','',true);
 perform public.claim_subscription_customer(c,'cus_QAonly');
 perform public.apply_subscription_provider_event(c,'evt_QAfirst',100,'customer.subscription.updated','cus_QAonly','sub_QAonly','pro','active',now(),now()+interval '30 days',false);
 perform public.apply_subscription_provider_event(c,'evt_QAfirst',100,'customer.subscription.updated','cus_QAonly','sub_QAonly','pro','active',now(),now()+interval '30 days',false);
 select count(*)into n from public.subscription_events where provider_event_id='evt_QAfirst';if n<>1 then raise exception 'Provider event replay';end if;
 perform public.apply_subscription_provider_event(c,'evt_QAold',99,'customer.subscription.updated','cus_QAonly','sub_QAonly','starter','active',now(),now()+interval '30 days',false);
 if public.effective_company_plan(c)<>'pro' then raise exception 'Stale event downgrade';end if;
end $$;
rollback;
select 'PASS: subscription plans, monthly limits, seat limits, trial, downgrade, role + plan, RLS, provider replay and isolation' as result,'All fixtures rolled back; no payments processed' as cleanup;
