-- Demonstration services are installed automatically per company by
-- 20260903000000_estimate_builder_rate_library.sql.
-- All sample values are fictional and must not be treated as market pricing.
