import{NextRequest,NextResponse}from"next/server";import{getAuthContext}from"@/lib/data";import{buildReport,loadReportSource,reportRange}from"@/lib/report-data";import{dateInTimezone,toCsv}from"@/lib/reporting";
export async function GET(request:NextRequest){const{company,supabase}=await getAuthContext();const params=request.nextUrl.searchParams;const range=reportRange({period:params.get("period")||undefined,from:params.get("from")||undefined,to:params.get("to")||undefined},dateInTimezone(String(company?.timezone||"America/New_York")));const source=await loadReportSource(supabase),report=buildReport(source,range,dateInTimezone(String(company?.timezone||"America/New_York"))),kind=params.get("kind")||"estimates";let headers:string[]=[],rows:unknown[][]=[];
if(kind==="estimates"||kind==="sales"){headers=["Estimate #","Date","Customer","Project","Status","Total"];rows=report.estimates.map(e=>[e.estimate_number,e.estimate_date,source.customers.find(c=>c.id===e.customer_id)?.name,e.project_name,e.status,e.total])}
else if(kind==="projects"||kind==="profitability"){headers=["Project #","Project","Customer","Status","Contract Value","Estimated Cost","Actual Cost","Estimated Profit","Projected Profit","Margin %"];rows=report.projectRows.filter(p=>report.projects.some(item=>item.id===p.id)).map(p=>[p.project_number,p.project_name,p.customer?.name,p.status,p.contractValue,p.estimated_internal_cost,p.actualCost,p.estimatedProfit,p.projectedProfit,p.projectedMargin])}
else if(kind==="invoices"){headers=["Invoice #","Date","Due Date","Customer","Project","Status","Total","Paid","Balance"];rows=report.invoices.map(i=>[i.invoice_number,i.invoice_date,i.due_date,source.customers.find(c=>c.id===i.customer_id)?.name,source.projects.find(p=>p.id===i.project_id)?.project_name,i.status,i.total,i.amount_paid,i.balance_due])}
else if(kind==="payments"){headers=["Date","Invoice #","Method","Reference","Amount","Voided"];rows=report.payments.map(p=>[p.payment_date,source.invoices.find(i=>i.id===p.invoice_id)?.invoice_number,p.payment_method,p.reference_number,p.amount,p.voided_at?"Yes":"No"])}
else if(kind==="costs"){headers=["Date","Project","Category","Description","Vendor","Amount"];rows=report.costs.map(c=>[c.cost_date,source.projects.find(p=>p.id===c.project_id)?.project_name,c.category,c.description,c.vendor,c.amount])}
else if(kind==="customers"){headers=["Customer","Company","Phone","Email","Created"];rows=report.newCustomers.map(c=>[c.name,c.company_name,c.phone,c.email,c.created_at.slice(0,10)])}
else return NextResponse.json({error:"Unsupported export"},{status:400});
return new NextResponse(toCsv(headers,rows),{headers:{"Content-Type":"text/csv; charset=utf-8","Content-Disposition":`attachment; filename="contractoros-${kind}-${range.from}-${range.to}.csv"`,"Cache-Control":"private, no-store"}})}
