import test from"node:test";import assert from"node:assert/strict";import{hasPermission,permissionForPath,permissionsFor,canManageMember,assignableRoles}from"../lib/permission-policy.ts";
test("Owner has every permission",()=>{for(const permission of permissionsFor("owner"))assert.equal(hasPermission("owner",permission),true)});
test("Admin manages team and finances but not owner-only financial settings",()=>{assert.equal(hasPermission("admin","team.manage"),true);assert.equal(hasPermission("admin","reports.financial"),true);assert.equal(hasPermission("admin","settings.financial"),false)});
test("Estimator can create and send estimates but cannot access team",()=>{assert.equal(hasPermission("estimator","estimates.create"),true);assert.equal(hasPermission("estimator","estimates.send"),true);assert.equal(hasPermission("estimator","team.view"),false)});
test("Project Manager can add costs but cannot view company reports",()=>{assert.equal(hasPermission("project_manager","project_costs.create"),true);assert.equal(hasPermission("project_manager","reports.view"),false)});
test("Employee only receives basic assigned-project access",()=>{assert.deepEqual(permissionsFor("employee"),["dashboard.view","assigned_projects.view"]);for(const sensitive of["financial.internal_costs","financial.profit","financial.margin","financial.revenue","invoices.view","payments.view","reports.view"]as const)assert.equal(hasPermission("employee",sensitive),false)});
test("role change immediately changes effective permissions",()=>{assert.equal(hasPermission("estimator","reports.view"),false);assert.equal(hasPermission("admin","reports.view"),true)});
test("sensitive routes map to server-side permission checks",()=>{assert.equal(permissionForPath("/team"),"team.view");assert.equal(permissionForPath("/reports"),"reports.view");assert.equal(permissionForPath("/settings/audit-log"),"audit.view");assert.equal(permissionForPath("/invoices/123"),"invoices.view");assert.equal(permissionForPath("/my-projects"),"assigned_projects.view")});
test("Admin controls cannot target or assign Owner",()=>{assert.equal(canManageMember("admin","owner"),false);assert.equal(assignableRoles("admin").includes("owner"),false);assert.equal(canManageMember("owner","owner"),true)});
