import test from "node:test";
import assert from "node:assert/strict";
import { effectivePlan, plans, hasPlanFeature, canUseFeature, getPlanLimit, monthlyPeriod, type SubscriptionState } from "../lib/plans.ts";
import { verifyStripeSignature } from "../lib/stripe-signature.ts";
import { createHmac } from "node:crypto";
const now = new Date("2026-09-09T12:00:00Z");
const base: SubscriptionState = { plan: "free", status: "free", trial_started_at: null, trial_ends_at: null, current_period_start: null, current_period_end: null, cancel_at_period_end: false, grace_ends_at: null, legacy_access: false, pending_plan: null, pending_effective_at: null };
test("new companies default to Free with three estimates", () => { assert.equal(effectivePlan(base, now), "free"); assert.equal(getPlanLimit("free", "maxEstimatesPerMonth"), 3); });
test("Starter estimates are unlimited but projects are not included", () => { assert.equal(getPlanLimit("starter", "maxEstimatesPerMonth"), null); assert.equal(hasPlanFeature("starter", "projects"), false); });
test("plan prices and member limits match the requested catalog", () => { assert.deepEqual(Object.values(plans).map(p => [p.priceMonthly,p.maxUsers]), [[0,1],[9.99,1],[19.99,3],[39.99,10]]); });
test("trial grants Pro until the exact server deadline", () => { const trial = { ...base, plan: "pro" as const, status: "trialing" as const, trial_ends_at: "2026-09-09T12:00:01Z" }; assert.equal(effectivePlan(trial,now),"pro"); assert.equal(effectivePlan(trial,new Date("2026-09-09T12:00:01Z")),"free"); });
test("Owner on Free cannot create invoices", () => assert.equal(canUseFeature("owner","free","invoices.create"),false));
test("Pro Owner can create invoices", () => assert.equal(canUseFeature("owner","pro","invoices.create"),true));
test("Business never overrides Employee financial restrictions", () => { for(const p of ["invoices.view","reports.view","payments.record","financial.profit"] as const)assert.equal(canUseFeature("employee","business",p),false); });
test("historical read permissions survive downgrade, writes do not", () => { assert.equal(canUseFeature("owner","free","invoices.view"),true); assert.equal(canUseFeature("owner","free","projects.edit"),false); });
test("canceled paid plan keeps access until the period end", () => { const s={...base,plan:"pro" as const,status:"canceled" as const,current_period_end:"2026-10-01T00:00:00Z"}; assert.equal(effectivePlan(s,now),"pro"); assert.equal(effectivePlan(s,new Date("2026-10-01T00:00:00Z")),"free"); });
test("past-due grace is bounded, not indefinitely renewed", () => { const s={...base,plan:"pro" as const,status:"past_due" as const,grace_ends_at:"2026-09-10T00:00:00Z"}; assert.equal(effectivePlan(s,now),"pro"); assert.equal(effectivePlan(s,new Date("2026-09-11")),"free"); });
test("incomplete payments do not unlock paid access", () => assert.equal(effectivePlan({...base,plan:"business",status:"incomplete"},now),"free"));
test("legacy access preserves existing company features without claiming payment", () => assert.equal(effectivePlan({...base,legacy_access:true},now),"business"));
test("monthly periods use UTC and roll over December correctly", () => {const p=monthlyPeriod(new Date("2026-12-31T23:59:59Z"));assert.equal(p.start.toISOString(),"2026-12-01T00:00:00.000Z");assert.equal(p.end.toISOString(),"2027-01-01T00:00:00.000Z");});
test("unsigned, forged, stale, and modified Stripe webhooks fail",()=>{const body='{"id":"evt_test"}',secret="test-webhook-only",timestamp=String(+now/1000),signature=createHmac("sha256",secret).update(`${timestamp}.${body}`).digest("hex"),header=`t=${timestamp},v1=${signature}`;assert.equal(verifyStripeSignature(body,header,secret,+now),true);assert.equal(verifyStripeSignature(body,null,secret,+now),false);assert.equal(verifyStripeSignature(body,header,"wrong",+now),false);assert.equal(verifyStripeSignature(body+" ",header,secret,+now),false);assert.equal(verifyStripeSignature(body,header,secret,+now+301000),false);});
