import test from"node:test";import assert from"node:assert/strict";import{readFileSync}from"node:fs";const sql=readFileSync(new URL("../supabase/migrations/20260907000000_team_roles_permissions.sql",import.meta.url),"utf8");
test("invitation tokens are random, hashed, expirable, and single-use",()=>{assert.match(sql,/gen_random_bytes\(32\)/);assert.match(sql,/digest\(raw_token,'sha256'\)/);assert.match(sql,/expires_at<=now\(\)/);assert.match(sql,/Invitation already used/);assert.match(sql,/Invitation revoked/)});
test("last active Owner is protected",()=>{assert.match(sql,/last active Owner cannot be deactivated/i);assert.match(sql,/last active Owner cannot change role/i)});
test("employee project projection excludes every sensitive financial key",()=>{const match=sql.match(/create or replace function public\.get_assigned_projects\(\)[\s\S]*?\$\$;/i);assert.ok(match);for(const key of["original_contract_value","estimated_internal_cost","total","amount_paid","balance_due","material_cost","labor_rate","overhead","markup","profit","margin"])assert.equal(match[0].includes(`'${key}'`),false)});
test("browser cannot write membership or role tables directly",()=>assert.match(sql,/revoke insert,update,delete on public\.company_members,public\.team_invitations,public\.project_members,public\.audit_events from authenticated,anon/));
test("permission checks do not trust browser company identity",()=>{assert.match(sql,/active_member_role\(target_company_id\)/);assert.match(sql,/user_id=auth\.uid\(\) and status='active'/)});
const guards=readFileSync(new URL("../supabase/migrations/20260908000000_team_event_and_assignment_guards.sql",import.meta.url),"utf8");
test("event helper remains private without blocking authorized workflow callers",()=>{assert.match(guards,/revoke execute on function public.record_estimate_event\(uuid,text,jsonb,uuid\) from public, anon, authenticated/);assert.equal(guards.includes("public.owns_company"),false)});
test("project assignment reads require current active company membership",()=>{assert.match(guards,/public.is_active_company_member\(p.company_id\)/);assert.match(guards,/using \(public.can_read_project_membership\(project_id, user_id\)\)/)});
