import { notFound } from "next/navigation";
import { ChangeOrderBuilder } from "@/components/change-order-builder";
import { ChangeOrderWorkflowActions } from "@/components/change-order-workflow-actions";
import { EstimateTimeline } from "@/components/estimate-timeline";
import { Badge,Card,PageHeader } from "@/components/ui";
import { getAuthContext } from "@/lib/data";
import { currency,shortDate } from "@/lib/utils";
import type { EstimateEvent } from "@/lib/database.types";
export default async function ChangeOrderPage({params}:{params:Promise<{id:string}>}){const{id}=await params;const{supabase}=await getAuthContext();const[{data:order},{data:items}]=await Promise.all([supabase.from("change_orders").select("*").eq("id",id).single(),supabase.from("change_order_items").select("*").eq("change_order_id",id).order("sort_order")]);if(!order)notFound();const[{data:estimate},{data:events},{data:approved}]=await Promise.all([supabase.from("estimates").select("*").eq("id",order.estimate_id).single(),supabase.from("estimate_events").select("*").eq("change_order_id",id).order("created_at",{ascending:false}),supabase.from("change_orders").select("total").eq("estimate_id",order.estimate_id).eq("status","approved").neq("id",id)]);if(!estimate)notFound();const previous=(approved||[]).reduce((sum,row)=>sum+Number(row.total),0);const locked=order.status==="approved"||order.status==="rejected";return <><PageHeader title={order.change_order_number} description={`${estimate.estimate_number} · ${estimate.project_name}`} action={<ChangeOrderWorkflowActions id={id} status={order.status} token={order.public_token}/>}/><div className="mb-6 grid gap-5 xl:grid-cols-[1fr_360px]"><Card className="p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase text-slate-400">Status</p><Badge tone={order.status==="approved"?"green":order.status==="rejected"?"red":order.status==="viewed"?"orange":order.status==="sent"?"blue":"slate"}>{order.status}</Badge></div><strong className="text-2xl">{currency(order.total)}</strong></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><Info label="Created" value={shortDate(order.created_at)}/><Info label="Sent" value={shortDate(order.sent_at)}/><Info label="First Viewed" value={shortDate(order.first_viewed_at)}/><Info label="Last Viewed" value={shortDate(order.last_viewed_at)}/><Info label="Approved / Rejected" value={shortDate(order.approved_at||order.rejected_at)}/><Info label="View Count" value={String(order.view_count)}/></div>{locked&&<p className="mt-5 rounded-lg bg-slate-50 p-4 text-sm text-slate-600">This customer response is locked and preserved in its approval snapshot.</p>}</Card><Card className="p-5"><h2 className="mb-4 font-semibold">Activity</h2><EstimateTimeline events={(events||[]) as EstimateEvent[]}/></Card></div>{!locked&&<ChangeOrderBuilder companyId={order.company_id} estimateId={order.estimate_id} number={order.change_order_number} taxPercent={order.sales_tax_percent} originalTotal={estimate.total} previousApproved={previous} existing={order} existingItems={items||[]}/>}</>}
function Info({label,value}:{label:string;value:string}){return <div><p className="text-xs text-slate-400">{label}</p><p className="font-semibold">{value}</p></div>}
