"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui";
import { plans, planIds, type SubscriptionAccess, type PlanId } from "@/lib/plans";
import { updateLocalBilling, requestDowngrade } from "@/app/(dashboard)/settings/billing/actions";
export function BillingControls({ subscription: s, stripeReady }: { subscription: SubscriptionAccess; stripeReady: boolean }) {
 const [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [lowerPlan,setLowerPlan] = useState("free"); const router = useRouter();
 async function downgrade() {setBusy(true);const result=await requestDowngrade(lowerPlan);setMessage(result.error||"Downgrade request saved. Free required seats first. Paid changes need provider confirmation; your current access has not changed.");setBusy(false);router.refresh();}
 async function local(action: "trial" | "cancel" | "resume") { setBusy(true); const result = await updateLocalBilling(action); setMessage(result.error || "Subscription updated."); setBusy(false); router.refresh(); }
 async function provider(action: "checkout" | "portal", plan?: PlanId) { setBusy(true); try { const response = await fetch(`/api/billing/${action}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(plan ? { plan } : {}) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Billing unavailable"); window.location.assign(data.url); } catch (error) { setMessage(error instanceof Error ? error.message : "Billing unavailable"); setBusy(false); } }
 return <div className="space-y-5">{!s.legacy_access && s.status === "free" && !s.trial_started_at && <Button loading={busy} onClick={() => local("trial")}>Start 14-Day Pro Trial</Button>}<div className="flex flex-wrap gap-3">{planIds.filter(id => id !== "free").map(id => <Button key={id} disabled={!stripeReady || busy || s.legacy_access} variant="secondary" onClick={() => provider("checkout", id)}>Choose {plans[id].name}</Button>)}<Button disabled={!stripeReady || busy} onClick={() => provider("portal")}>Manage Billing</Button></div>{!stripeReady && <p className="rounded-lg bg-slate-100 p-4 text-sm text-slate-600">Paid upgrades, paid downgrades and the billing portal are unavailable until Stripe is connected. No card payments are being processed.</p>}{!s.legacy_access && s.status === "trialing" && <Button variant="secondary" disabled={busy} onClick={() => local(s.cancel_at_period_end ? "resume" : "cancel")}>{s.cancel_at_period_end ? "Resume Subscription" : "Cancel at Trial End / Downgrade to Free"}</Button>}{stripeReady && <p className="text-sm text-slate-500">Use Manage Billing to schedule a downgrade, cancel at the end of your billing period, or resume before the period ends.</p>}{!s.legacy_access&&s.plan!=="free"&&<div className="flex flex-wrap gap-3"><select aria-label="Downgrade plan" className="min-h-11 rounded-lg border px-3" value={lowerPlan} onChange={e=>setLowerPlan(e.target.value)}>{planIds.filter(id=>planIds.indexOf(id)<planIds.indexOf(s.plan)).map(id=><option key={id} value={id}>{plans[id].name}</option>)}</select><Button variant="secondary" disabled={busy} onClick={downgrade}>Review Downgrade</Button></div>}{s.pending_plan&&!s.pending_effective_at&&<p className="text-sm text-orange-700">Pending request: {plans[s.pending_plan].name}. Not yet confirmed by the billing provider.</p>}{message && <p role="status" className="text-sm font-semibold text-orange-700">{message}</p>}</div>;
}
