"use client";
import { useMemo,useState } from "react";
import { ArrowDown,ArrowUp,Plus,Save,Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { Button,Card,Input,Select,Textarea } from "@/components/ui";
import { createClient } from "@/lib/supabase/client";
import { calculateChangeOrder } from "@/lib/change-order-calculations";
import { ESTIMATE_UNITS,unitLabel } from "@/lib/estimate-options";
import { currency } from "@/lib/utils";
import type { ChangeOrder,ChangeOrderItem } from "@/lib/database.types";

type Item={key:string;description:string;quantity:number;unit:string;unitPrice:number;taxable:boolean};
const blank=():Item=>({key:crypto.randomUUID(),description:"",quantity:1,unit:"each",unitPrice:0,taxable:true});
export function ChangeOrderBuilder({companyId,estimateId,number,taxPercent,originalTotal,previousApproved,existing,existingItems=[]}:{companyId:string;estimateId:string;number:string;taxPercent:number;originalTotal:number;previousApproved:number;existing?:ChangeOrder;existingItems?:ChangeOrderItem[]}){
 const router=useRouter();const[loading,setLoading]=useState(false);const[tax,setTax]=useState(existing?.sales_tax_percent??taxPercent);const[items,setItems]=useState<Item[]>(existingItems.length?existingItems.map(item=>({key:item.id,description:item.description,quantity:item.quantity,unit:item.unit,unitPrice:item.unit_price,taxable:item.taxable})):[blank()]);
 const calc=useMemo(()=>calculateChangeOrder(items.map(item=>({quantity:item.quantity,unitPrice:item.unitPrice,taxable:item.taxable})),tax,originalTotal,previousApproved),[items,tax,originalTotal,previousApproved]);
 function update<K extends keyof Item>(key:string,field:K,value:Item[K]){setItems(rows=>rows.map(row=>row.key===key?{...row,[field]:value}:row));}
 function move(index:number,direction:number){setItems(rows=>{const next=[...rows],target=index+direction;if(target<0||target>=next.length)return rows;[next[index],next[target]]=[next[target],next[index]];return next;});}
 async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!items.length||items.some(item=>!item.description.trim())){toast.error("Every line item needs a description.");return;}setLoading(true);const form=new FormData(event.currentTarget);const header={company_id:companyId,estimate_id:estimateId,change_order_number:String(form.get("number")),change_date:String(form.get("date")),description:String(form.get("description")),sales_tax_percent:tax,subtotal:calc.subtotal,sales_tax_amount:calc.tax,total:calc.total,original_contract_value:originalTotal,previous_changes_value:previousApproved,new_contract_value:calc.newContractValue};const supabase=createClient();let id=existing?.id;if(id){const{error}=await supabase.from("change_orders").update(header).eq("id",id);if(error){toast.error(error.message);setLoading(false);return;}const{error:removeError}=await supabase.from("change_order_items").delete().eq("change_order_id",id);if(removeError){toast.error(removeError.message);setLoading(false);return;}}else{const{data,error}=await supabase.from("change_orders").insert(header).select("id").single();if(error||!data){toast.error(error?.message||"Could not save change order.");setLoading(false);return;}id=data.id;}const{error}=await supabase.from("change_order_items").insert(items.map((item,index)=>({change_order_id:id!,company_id:companyId,sort_order:index,description:item.description.trim(),quantity:item.quantity,unit:item.unit,unit_price:item.unitPrice,taxable:item.taxable})));setLoading(false);if(error){toast.error(error.message);return;}toast.success("Change order saved.");router.push(`/change-orders/${id}`);router.refresh();}
 return <form onSubmit={save} className="grid gap-6"><Card className="grid gap-4 p-5 md:grid-cols-3"><Input name="number" label="Change Order Number *" defaultValue={existing?.change_order_number||number} required/><Input name="date" label="Date *" type="date" defaultValue={existing?.change_date||new Date().toISOString().slice(0,10)} required/><Input label="Sales Tax %" type="number" min="0" max="100" step="0.001" value={tax} onChange={e=>setTax(Number(e.target.value)||0)}/><Textarea name="description" label="Description / Reason for Change *" defaultValue={existing?.description||""} required className="md:col-span-3"/></Card>
 <Card className="overflow-hidden"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-semibold">Change Order Items</h2><p className="text-sm text-slate-500">Simple customer-facing additions or credits.</p></div><Button type="button" size="sm" onClick={()=>setItems(rows=>[...rows,blank()])}><Plus className="h-4 w-4"/>Add Item</Button></div><div className="divide-y">{items.map((item,index)=><div key={item.key} className="grid gap-3 p-4 md:grid-cols-[1fr_140px_180px_160px_110px_auto] md:items-end"><Input label="Description *" value={item.description} onChange={e=>update(item.key,"description",e.target.value)}/><Input label="Quantity" type="number" min="0" step="0.001" value={item.quantity} onChange={e=>update(item.key,"quantity",Number(e.target.value)||0)}/><Select label="Unit" value={item.unit} onChange={e=>update(item.key,"unit",e.target.value)}>{ESTIMATE_UNITS.map(([value,label])=><option key={value} value={value}>{label}</option>)}</Select><Input label="Unit Price" type="number" min="0" step="0.01" value={item.unitPrice} onChange={e=>update(item.key,"unitPrice",Number(e.target.value)||0)}/><label className="flex h-11 items-center gap-2 rounded-lg border px-3 text-sm"><input type="checkbox" checked={item.taxable} onChange={e=>update(item.key,"taxable",e.target.checked)} className="accent-orange-500"/>Taxable</label><div className="flex gap-1"><button type="button" aria-label="Move up" disabled={!index} onClick={()=>move(index,-1)} className="rounded-lg p-2 hover:bg-slate-100 disabled:opacity-30"><ArrowUp className="h-4 w-4"/></button><button type="button" aria-label="Move down" disabled={index===items.length-1} onClick={()=>move(index,1)} className="rounded-lg p-2 hover:bg-slate-100 disabled:opacity-30"><ArrowDown className="h-4 w-4"/></button><button type="button" aria-label="Delete item" disabled={items.length===1} onClick={()=>setItems(rows=>rows.filter(row=>row.key!==item.key))} className="rounded-lg p-2 text-red-600 hover:bg-red-50 disabled:opacity-30"><Trash2 className="h-4 w-4"/></button></div><div className="md:col-span-6 text-right text-sm text-slate-500">{item.quantity} {unitLabel(item.unit)} × {currency(item.unitPrice)} = <strong className="text-slate-900">{currency(calc.rows[index].amount)}</strong></div></div>)}</div></Card>
 <div className="grid gap-6 lg:grid-cols-[1fr_420px]"><Card className="p-5"><h2 className="font-semibold">Contract Value</h2><p className="mt-1 text-sm text-slate-500">The new value includes only approved prior changes plus this current change order.</p></Card><Card className="space-y-2 p-5 text-sm"><Row label="Original Approved Estimate" value={originalTotal}/><Row label="Previously Approved Change Orders" value={previousApproved}/><Row label="Current Subtotal" value={calc.subtotal}/><Row label="Tax" value={calc.tax}/><Row label="Current Change Order" value={calc.total}/><div className="flex justify-between border-t-2 border-slate-900 pt-3 text-lg font-bold"><span>NEW CONTRACT VALUE</span><span>{currency(calc.newContractValue)}</span></div></Card></div>
 <div className="sticky bottom-3 flex justify-end rounded-xl border bg-white/95 p-3 shadow-lg"><Button loading={loading}><Save className="h-4 w-4"/>Save Draft</Button></div></form>;
}
function Row({label,value}:{label:string;value:number}){return <div className="flex justify-between"><span className="text-slate-500">{label}</span><span>{currency(value)}</span></div>}
