import Image from "next/image";
import { CheckCircle2, HardHat, MapPin } from "lucide-react";
import { PrintButton } from "@/components/print-button";
import { PublicApprovalControls } from "@/components/public-approval-controls";
import { currency, shortDate } from "@/lib/utils";
import { unitLabel } from "@/lib/estimate-options";
import type { PublicDocumentData } from "@/lib/public-document-types";

export function PublicDocument({ data, token, justApproved=false }: { data: PublicDocumentData; token: string; justApproved?: boolean }) {
  const estimate = data.kind === "estimate" ? data.estimate : null; const change = data.kind === "change_order" ? data.change_order : null;
  const number = estimate?.estimate_number || change!.number; const project = estimate?.project_name || change!.project_name;
  const approved = data.status === "approved"; const title = approved ? `Approved ${data.kind === "estimate" ? "Estimate" : "Change Order"}` : data.kind === "estimate" ? "Estimate" : "Change Order";
  const total = data.summary.total;
  return <main className="min-h-screen bg-slate-100 px-3 py-4 text-slate-900 sm:px-6 sm:py-8">
    <div className="no-print mx-auto mb-4 flex max-w-5xl justify-end"><PrintButton label={approved?`Download Approved ${data.kind==="estimate"?"Estimate":"Change Order"}`:"Download PDF"}/></div>
    {justApproved&&approved&&<section className="no-print mx-auto mb-4 max-w-5xl rounded-2xl border border-emerald-200 bg-emerald-50 p-6 text-center"><CheckCircle2 className="mx-auto h-10 w-10 text-emerald-600"/><h2 className="mt-2 text-2xl font-bold text-emerald-950">{data.kind==="estimate"?"Estimate":"Change Order"} Approved</h2><p className="mt-1 text-sm text-emerald-800">{number} · {project} · {currency(total)}</p><div className="mt-4"><PrintButton label={`Download Approved ${data.kind==="estimate"?"Estimate":"Change Order"}`}/></div></section>}
    <article className="mx-auto min-h-[1056px] max-w-5xl bg-white p-5 shadow-sm sm:p-10 print:min-h-0 print:p-0 print:shadow-none">
      <header className="flex flex-col justify-between gap-6 border-b-2 border-slate-900 pb-7 sm:flex-row sm:items-start"><div className="flex items-center gap-4">{data.company.logo_url?<Image src={data.company.logo_url} alt={`${data.company.name} logo`} width={80} height={80} className="h-16 w-16 object-contain sm:h-20 sm:w-20"/>:<span className="grid h-16 w-16 shrink-0 place-items-center rounded-xl bg-orange-500 text-white"><HardHat className="h-8 w-8"/></span>}<div><h1 className="text-xl font-bold sm:text-2xl">{data.company.name}</h1><div className="mt-1 text-xs leading-5 text-slate-500">{data.company.address&&<p>{data.company.address}, {data.company.city}, {data.company.state} {data.company.zip}</p>}{(data.company.phone||data.company.email)&&<p>{[data.company.phone,data.company.email].filter(Boolean).join(" · ")}</p>}{data.company.website&&<p>{data.company.website}</p>}{data.company.contractor_license&&<p>License: {data.company.contractor_license}</p>}</div></div></div><div className="sm:text-right"><p className="text-xs font-bold uppercase tracking-[.18em] text-orange-600">{title}</p><p className="mt-1 text-2xl font-bold">{number}</p><p className="mt-2 text-xs text-slate-500">Date: {shortDate(estimate?.estimate_date||change?.date)}</p>{estimate&&<p className="text-xs text-slate-500">Valid until: {shortDate(estimate.valid_until)}</p>}{approved&&<span className="mt-2 inline-flex items-center gap-1 rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700"><CheckCircle2 className="h-3.5 w-3.5"/>Electronically Approved</span>}</div></header>
      <section className="grid gap-6 py-7 sm:grid-cols-2"><div><Label>Prepared For</Label><p className="font-bold">{data.customer.name}</p>{data.customer.company_name&&<p className="text-sm text-slate-600">{data.customer.company_name}</p>}</div>{data.job_site&&<div><Label>Job Address</Label><p className="flex items-center gap-1.5 font-bold"><MapPin className="h-4 w-4 text-orange-500"/>{data.job_site.job_name}</p><p className="mt-1 text-sm text-slate-500">{data.job_site.address}<br/>{data.job_site.city}, {data.job_site.state} {data.job_site.zip}</p></div>}</section>
      <section className="mb-7 rounded-xl bg-slate-50 p-5"><h2 className="text-xl font-bold">{project}</h2>{estimate?.scope_of_work&&<><Label className="mt-4">Scope of Work</Label><p className="mt-1 whitespace-pre-wrap text-sm leading-6 text-slate-600">{estimate.scope_of_work}</p></>}{change&&<><Label className="mt-4">Description / Reason for Change</Label><p className="mt-1 whitespace-pre-wrap text-sm leading-6 text-slate-600">{change.description}</p><p className="mt-3 text-xs text-slate-500">Original Estimate: {change.original_estimate_number}</p></>}</section>
      <section className="overflow-hidden rounded-xl border border-slate-200"><div className="hidden grid-cols-[1fr_100px_110px_130px] bg-slate-900 px-4 py-3 text-xs font-semibold uppercase tracking-wide text-white sm:grid"><span>Description</span><span className="text-right">Quantity</span><span className="text-center">Unit</span><span className="text-right">Amount</span></div><div className="divide-y divide-slate-100">{data.items.map((item,index)=><div key={`${item.description}-${index}`} className="grid grid-cols-[1fr_auto] gap-3 p-4 sm:grid-cols-[1fr_100px_110px_130px] sm:items-center"><p className="font-medium">{item.description}</p><p className="text-right font-semibold sm:order-last">{currency(item.amount)}</p><p className="text-xs text-slate-500 sm:text-right sm:text-sm">{item.quantity}</p><p className="text-right text-xs text-slate-500 sm:text-center sm:text-sm">{unitLabel(item.unit)}</p></div>)}</div></section>
      {data.kind==="estimate"?<section className="ml-auto mt-6 w-full max-w-sm space-y-2 text-sm"><Summary label="Subtotal" value={data.summary.subtotal}/>{data.summary.discount>0&&<Summary label="Discount" value={`-${currency(data.summary.discount)}`}/>}<Summary label="Tax" value={data.summary.tax}/><Total value={data.summary.total}/><Summary accent label="Deposit Required" value={data.summary.deposit}/><Summary label="Remaining Balance" value={data.summary.remaining_balance}/></section>:<section className="ml-auto mt-6 w-full max-w-md space-y-2 text-sm"><Summary label="Subtotal" value={data.summary.subtotal}/><Summary label="Tax" value={data.summary.tax}/><Total label="CHANGE ORDER TOTAL" value={data.summary.total}/><div className="mt-5 space-y-2 rounded-xl bg-slate-50 p-4"><Summary label="Original Approved Estimate" value={data.summary.original_contract_value}/><Summary label="Previously Approved Changes" value={data.summary.previous_changes_value}/><Summary label="Current Change Order" value={data.summary.total}/><div className="flex justify-between border-t border-slate-300 pt-3 text-lg font-bold"><span>NEW CONTRACT VALUE</span><span>{currency(data.summary.new_contract_value)}</span></div></div></section>}
      {data.kind==="estimate"&&<section className="mt-8 grid gap-5 border-t border-slate-200 pt-6 sm:grid-cols-2">{data.details.estimated_start_date&&<Info label="Estimated Start Date" value={shortDate(data.details.estimated_start_date)}/>} {data.details.estimated_completion_date&&<Info label="Estimated Completion Date" value={shortDate(data.details.estimated_completion_date)}/>} {data.details.payment_terms&&<Info label="Payment Terms" value={data.details.payment_terms}/>} {data.details.inclusions&&<Info label="Inclusions" value={data.details.inclusions}/>} {data.details.exclusions&&<Info label="Exclusions" value={data.details.exclusions}/>} {data.details.customer_notes&&<Info label="Notes" value={data.details.customer_notes}/>}</section>}
      {data.approval&&<section className="mt-8 rounded-xl border border-emerald-200 bg-emerald-50 p-5"><div className="flex items-center gap-2 text-emerald-800"><CheckCircle2 className="h-5 w-5"/><h2 className="font-bold">Electronically Approved</h2></div><div className="mt-4 grid gap-4 sm:grid-cols-3"><Info label="Approved By" value={data.approval.approved_by}/><Info label="Email" value={data.approval.email}/><Info label="Approved Date" value={shortDate(data.approval.approved_at)}/></div><div className="mt-5 border-t border-emerald-200 pt-4">{data.approval.signature_type==="drawn"?<Image src={data.approval.signature_data} unoptimized alt="Customer signature" width={420} height={140} className="h-24 w-auto max-w-full object-contain object-left"/>:<p className="font-serif text-3xl italic">{data.approval.signature_data}</p>}<p className="mt-2 text-xs text-emerald-700">Electronic signature recorded {new Date(data.approval.approved_at).toLocaleString("en-US")}.</p></div></section>}
      <PublicApprovalControls kind={data.kind==="estimate"?"estimate":"change-order"} token={token} number={number} total={total} status={data.status} expired={data.kind==="estimate"&&data.expired}/>
    </article>
  </main>;
}

function Label({children,className=""}:{children:React.ReactNode;className?:string}){return <p className={`${className} mb-2 text-xs font-bold uppercase tracking-wide text-slate-400`}>{children}</p>}
function Summary({label,value,accent}:{label:string;value:number|string;accent?:boolean}){return <div className={`flex justify-between ${accent?"rounded-md bg-orange-50 px-3 py-2 font-semibold text-orange-800":""}`}><span className={accent?"":"text-slate-500"}>{label}</span><span>{typeof value==="number"?currency(value):value}</span></div>}
function Total({value,label="TOTAL ESTIMATE"}:{value:number;label?:string}){return <div className="flex justify-between border-t-2 border-slate-900 pt-3 text-xl font-bold"><span>{label}</span><span>{currency(value)}</span></div>}
function Info({label,value}:{label:string;value:string}){return <div><Label>{label}</Label><p className="whitespace-pre-wrap text-sm leading-6 text-slate-600">{value}</p></div>}
