import Image from "next/image";
import { CheckCircle2, HardHat, MapPin } from "lucide-react";
import { PrintButton } from "@/components/print-button";
import { currency, shortDate } from "@/lib/utils";
import { unitLabel } from "@/lib/estimate-options";
import type { PublicInvoice as Data } from "@/lib/public-document-types";

export function PublicInvoice({data}:{data:Data}) {
  const paid=data.status==="paid";
  return <main className="min-h-screen bg-slate-100 px-3 py-4 text-slate-900 sm:px-6 sm:py-8">
    <div className="no-print mx-auto mb-4 flex max-w-5xl justify-end"><PrintButton label="Download Invoice PDF"/></div>
    <article className="mx-auto min-h-[1056px] max-w-5xl bg-white p-5 shadow-sm sm:p-10 print:min-h-0 print:p-0 print:shadow-none">
      <header className="flex flex-col justify-between gap-6 border-b-2 border-slate-900 pb-7 sm:flex-row">
        <div className="flex items-center gap-4">{data.company.logo_url?<Image src={data.company.logo_url} alt="Company logo" width={80} height={80} className="h-20 w-20 object-contain"/>:<span className="grid h-16 w-16 place-items-center rounded-xl bg-orange-500 text-white"><HardHat/></span>}<div><h1 className="text-2xl font-bold">{data.company.name}</h1><p className="mt-1 text-xs leading-5 text-slate-500">{data.company.address}<br/>{[data.company.city,data.company.state,data.company.zip].filter(Boolean).join(", ")}<br/>{[data.company.phone,data.company.email].filter(Boolean).join(" · ")}</p></div></div>
        <div className="sm:text-right"><p className="text-xs font-bold uppercase tracking-[.18em] text-orange-600">{data.invoice.invoice_type} invoice</p><p className="text-2xl font-bold">{data.invoice.invoice_number}</p><p className="mt-2 text-xs text-slate-500">Invoice date: {shortDate(data.invoice.invoice_date)}</p><p className="text-xs text-slate-500">Due date: {shortDate(data.invoice.due_date)}</p>{paid&&<span className="mt-3 inline-flex items-center gap-1 rounded-full bg-emerald-100 px-4 py-2 font-bold text-emerald-700"><CheckCircle2 className="h-4 w-4"/>PAID</span>}</div>
      </header>
      <section className="grid gap-6 py-7 sm:grid-cols-2"><div><Label>Bill To</Label><p className="font-bold">{data.customer.name}</p>{data.customer.company_name&&<p className="text-sm text-slate-600">{data.customer.company_name}</p>}{data.customer.billing_address&&<p className="mt-1 text-sm text-slate-500">{data.customer.billing_address}</p>}</div>{data.job_site&&<div><Label>Job Site</Label><p className="flex items-center gap-1.5 font-bold"><MapPin className="h-4 w-4 text-orange-500"/>{data.job_site.job_name}</p><p className="text-sm text-slate-500">{data.job_site.address}<br/>{data.job_site.city}, {data.job_site.state} {data.job_site.zip}</p></div>}</section>
      <section className="mb-6 grid gap-4 rounded-xl bg-slate-50 p-4 text-sm sm:grid-cols-3">{data.project&&<Info label="Project" value={`${data.project.project_number} · ${data.project.project_name}`}/>} {data.estimate&&<Info label="Estimate Reference" value={data.estimate.estimate_number}/>} {data.invoice.po_number&&<Info label="PO Number" value={data.invoice.po_number}/>}</section>
      <section className="overflow-hidden rounded-xl border"><div className="hidden grid-cols-[1fr_90px_90px_120px_120px] bg-slate-900 px-4 py-3 text-xs font-bold uppercase text-white sm:grid"><span>Description</span><span className="text-right">Quantity</span><span className="text-center">Unit</span><span className="text-right">Unit Price</span><span className="text-right">Amount</span></div><div className="divide-y">{data.items.map((item,index)=><div key={index} className="grid grid-cols-[1fr_auto] gap-2 p-4 sm:grid-cols-[1fr_90px_90px_120px_120px] sm:items-center"><strong className="sm:order-1">{item.description}</strong><span className="text-right font-semibold sm:order-5">{currency(item.amount)}</span><span className="text-xs text-slate-500 sm:order-2 sm:text-right">{item.quantity}</span><span className="text-right text-xs text-slate-500 sm:order-3 sm:text-center">{unitLabel(item.unit)}</span><span className="hidden text-right sm:order-4 sm:block">{currency(item.unit_price)}</span></div>)}</div></section>
      <section className="ml-auto mt-6 w-full max-w-sm space-y-2 text-sm"><Row label="Subtotal" value={data.summary.subtotal}/>{data.summary.discount>0&&<Row label="Discount" value={`-${currency(data.summary.discount)}`}/>}<Row label="Tax" value={data.summary.tax}/><div className="flex justify-between border-t-2 border-slate-900 pt-3 text-xl font-bold"><span>TOTAL</span><span>{currency(data.summary.total)}</span></div><Row label="Amount Paid" value={data.summary.amount_paid}/><div className="flex justify-between rounded-xl bg-orange-50 p-4 text-xl font-black text-orange-900"><span>BALANCE DUE</span><span>{currency(data.summary.balance_due)}</span></div></section>
      {data.payments.length>0&&<section className="mt-8"><h2 className="font-bold">Payments Applied</h2><div className="mt-3 divide-y rounded-xl border">{data.payments.map((payment,index)=><div key={index} className="flex justify-between gap-4 p-3 text-sm"><span>{shortDate(payment.payment_date)} · {payment.payment_method.replaceAll("_"," ")}{payment.reference_number?` · ${payment.reference_number}`:""}</span><strong>{currency(payment.amount)}</strong></div>)}</div></section>}
      <section className="mt-8 grid gap-5 border-t pt-6 sm:grid-cols-2">{data.invoice.payment_terms&&<Info label="Payment Terms" value={data.invoice.payment_terms}/>} {data.invoice.customer_notes&&<Info label="Notes" value={data.invoice.customer_notes}/>}</section>
    </article>
  </main>
}
function Label({children}:{children:React.ReactNode}){return <p className="mb-2 text-xs font-bold uppercase tracking-wide text-slate-400">{children}</p>}
function Info({label,value}:{label:string;value:string}){return <div><Label>{label}</Label><p className="whitespace-pre-wrap text-sm text-slate-600">{value}</p></div>}
function Row({label,value}:{label:string;value:number|string}){return <div className="flex justify-between"><span className="text-slate-500">{label}</span><span>{typeof value==="number"?currency(value):value}</span></div>}
