import type{MemberRole}from"@/lib/database.types";
export const permissions=["dashboard.view","customers.view","customers.create","customers.edit","customers.delete","estimates.view","estimates.create","estimates.edit","estimates.send","estimates.delete","rate_library.view","rate_library.manage","projects.view","projects.create","projects.edit","assigned_projects.view","change_orders.view","change_orders.create","change_orders.send","invoices.view","invoices.create","invoices.send","payments.view","payments.record","project_costs.view","project_costs.create","reports.view","reports.financial","team.view","team.manage","settings.company","settings.financial","financial.internal_costs","financial.profit","financial.margin","financial.revenue","financial.project_summary","audit.view"]as const;
export type Permission=typeof permissions[number];
const rolePermissions:Record<MemberRole,readonly Permission[]>={owner:permissions,admin:permissions.filter(p=>p!=="settings.financial"&&p!=="assigned_projects.view"),estimator:["dashboard.view","customers.view","customers.create","customers.edit","estimates.view","estimates.create","estimates.edit","estimates.send","rate_library.view","financial.internal_costs"],project_manager:["financial.project_summary","dashboard.view","estimates.view","customers.view","projects.view","projects.edit","change_orders.view","change_orders.create","change_orders.send","invoices.view","invoices.create","invoices.send","project_costs.view","project_costs.create","financial.internal_costs"],employee:["dashboard.view","assigned_projects.view"]};
export function hasPermission(role:MemberRole|undefined|null,permission:Permission){return !!role&&rolePermissions[role].includes(permission)}
export function permissionsFor(role:MemberRole){return rolePermissions[role]}
export function canManageMember(actor:MemberRole,target:MemberRole){return hasPermission(actor,"team.manage")&&(target!=="owner"||actor==="owner")}
export function assignableRoles(actor:MemberRole):MemberRole[]{return (["admin","estimator","project_manager","employee","owner"] as MemberRole[]).filter(role=>role!=="owner"||actor==="owner")}
export function permissionForPath(path:string):Permission|null{if(path==="/estimates/new")return"estimates.create";if(path==="/customers/new")return"customers.create";if(path.startsWith("/rate-library/"))return"rate_library.manage";if(path==="/invoices/new")return"invoices.create";if(path==="/change-orders/new")return"change_orders.create";if(path.startsWith("/settings/audit-log"))return"audit.view";if(path.startsWith("/team"))return"team.view";if(path.startsWith("/reports")||path.startsWith("/api/reports"))return"reports.view";if(path.startsWith("/rate-library"))return"rate_library.view";if(path.startsWith("/payments"))return"payments.view";if(path.startsWith("/invoices"))return"invoices.view";if(path.startsWith("/change-orders"))return"change_orders.view";if(path.startsWith("/estimates"))return"estimates.view";if(path.startsWith("/customers"))return"customers.view";if(path.startsWith("/projects"))return"projects.view";if(path.startsWith("/my-projects"))return"assigned_projects.view";if(path.startsWith("/settings"))return"settings.company";if(path.startsWith("/dashboard")||path.startsWith("/profile"))return"dashboard.view";return null}
