import Link from "next/link";
import { FolderKanban } from "lucide-react";
import { Badge, Card, EmptyState, PageHeader } from "@/components/ui";
import { getAuthContext } from "@/lib/data";
import { projectFinancials } from "@/lib/financial-calculations";
import { currency } from "@/lib/utils";
const tone={upcoming:"blue",in_progress:"orange",on_hold:"slate",completed:"green",cancelled:"red"} as const;
export default async function ProjectsPage(){const{supabase}=await getAuthContext();const[{data:projects},{data:customers},{data:invoices},{data:changes}]=await Promise.all([supabase.from("projects").select("*").order("created_at",{ascending:false}),supabase.from("customers").select("id,name"),supabase.from("invoices").select("project_id,total,amount_paid,status"),supabase.from("change_orders").select("estimate_id,total,status")]);return <><PageHeader title="Projects" description="Approved work, billing progress, and customer balances."/><Card className="overflow-hidden">{!projects?.length?<EmptyState icon={<FolderKanban/>} title="No projects yet" description="Open an approved estimate and select Create Project."/>:<div className="divide-y">{projects.map(p=>{const customer=customers?.find(c=>c.id===p.customer_id);const projectInvoices=(invoices||[]).filter(i=>i.project_id===p.id&&i.status!=="void");const invoiced=projectInvoices.reduce((s,i)=>s+Number(i.total),0);const paid=projectInvoices.reduce((s,i)=>s+Number(i.amount_paid),0);const approvedChanges=(changes||[]).filter(c=>c.estimate_id===p.estimate_id&&c.status==="approved").reduce((s,c)=>s+Number(c.total),0);const f=projectFinancials(p.original_contract_value,approvedChanges,invoiced,paid,0);return <Link key={p.id} href={`/projects/${p.id}`} className="grid gap-3 p-4 hover:bg-slate-50 sm:grid-cols-[1.4fr_1fr_repeat(3,130px)_110px] sm:items-center"><div><p className="font-semibold">{p.project_name}</p><p className="text-xs text-slate-500">{p.project_number}</p></div><p className="text-sm">{customer?.name}</p><Metric label="Contract" value={currency(f.currentContractValue)}/><Metric label="Invoiced" value={currency(f.totalInvoiced)}/><Metric label="Paid" value={currency(f.totalPaid)}/><Badge tone={tone[p.status]}>{p.status.replaceAll("_"," ")}</Badge></Link>})}</div>}</Card></>}
function Metric({label,value}:{label:string;value:string}){return <div><p className="text-xs text-slate-400">{label}</p><p className="font-semibold">{value}</p></div>}
