import Link from "next/link";
import { PageHeader, Card, Badge } from "@/components/ui";
import { BillingControls } from "@/components/billing-controls";
import { getSubscriptionContext } from "@/lib/subscriptions";
import { plans } from "@/lib/plans";
import { stripeConfigured } from "@/lib/stripe-billing";
function Usage({ label, used, limit }: { label: string; used: number; limit: number | null }) {
 return <div><div className="flex justify-between gap-3 text-sm"><strong>{label}</strong><span>{used} / {limit ?? "Unlimited"}</span></div><progress className="mt-3 h-2 w-full overflow-hidden rounded-full accent-orange-500" value={limit ? Math.min(used, limit) : 0} max={limit || 1} aria-label={label}/></div>;
}
export default async function BillingPage() {
 const { subscription: s } = await getSubscriptionContext(true); const plan = plans[s.effective_plan];
 const date = (value: string | null) => value ? new Date(value).toLocaleDateString("en-US", { timeZone: "UTC" }) : "—";
 const seats = (s.active_team_members || 0) + (s.pending_invites || 0), targetLimit = s.pending_plan ? plans[s.pending_plan].maxUsers : plan.maxUsers;
 return <><PageHeader title="Plan & Billing" description="Your ContractorOS SaaS subscription. This is separate from customer invoices and payments." action={<Link className="text-sm font-semibold text-orange-600" href="/pricing">Compare all plans</Link>}/><div className="grid gap-6 lg:grid-cols-2"><Card className="p-6"><div className="flex justify-between"><h2 className="text-2xl font-bold">{plan.name}</h2><Badge tone={s.status === "past_due" ? "red" : "orange"}>{s.legacy_access ? "Legacy access" : s.status}</Badge></div><p className="mt-4 text-3xl font-bold">${plan.priceMonthly.toFixed(2)}<small className="text-sm font-normal text-slate-500"> / month list price</small></p><p className="mt-2 text-sm text-slate-500">{s.legacy_access ? "Your existing access is preserved. This is not a paid subscription." : s.status === "trialing" ? "No charge during your 14-day trial." : s.effective_plan === "free" ? "No recurring charge." : "Actual billing is managed by your payment provider."}</p><dl className="mt-6 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-slate-500">Trial end</dt><dd>{date(s.trial_ends_at)}</dd></div><div><dt className="text-slate-500">Billing period</dt><dd>{date(s.current_period_start)} – {date(s.current_period_end)}</dd></div><div><dt className="text-slate-500">Grace period ends</dt><dd>{date(s.grace_ends_at)}</dd></div><div><dt className="text-slate-500">Cancel at period end</dt><dd>{s.cancel_at_period_end ? "Yes" : "No"}</dd></div></dl></Card><Card className="space-y-7 p-6"><h2 className="text-lg font-bold">Plan Usage</h2><Usage label="Estimates this month" used={s.estimates_created || 0} limit={plan.maxEstimatesPerMonth}/><Usage label="Team seats" used={seats} limit={plan.maxUsers}/><p className="text-xs text-slate-500">{s.active_team_members} active members + {s.pending_invites} valid pending invitations. Estimate usage resets {date(s.period_end)} at 00:00 UTC. Deleted estimates still count.</p></Card></div>{seats > targetLimit && <Card className="mt-6 border-orange-300 bg-orange-50 p-5"><p>Your account has {seats} occupied or reserved seats. {plans[s.pending_plan || s.effective_plan].name} supports {targetLimit}. Deactivate members or revoke pending invitations to free {seats - targetLimit} seats. No users are deleted automatically.</p><Link className="mt-2 inline-block font-semibold underline" href="/team">Manage team</Link></Card>}<Card className="mt-6 p-6"><h2 className="mb-4 text-lg font-bold">Subscription options</h2><BillingControls subscription={s} stripeReady={stripeConfigured()}/></Card><p className="mt-5 text-sm text-slate-500">After trial expiration, cancellation or downgrade, historical documents remain readable according to your role. Paid-only creation and editing are locked. Annual plans are not enabled.</p></>;
}
