import assert from "node:assert/strict";
import {createClient} from "@supabase/supabase-js";
const company="e64f0776-836b-44a2-a308-0c2ff8010170";
const password=process.env.CONTRACTOROS_QA_PASSWORD;
if(!password)throw new Error("Set CONTRACTOROS_QA_PASSWORD for isolated QA accounts");
const client=()=>createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const ok=async request=>{const {data,error}=await request;if(error)throw new Error(error.message);return data;};
const denied=async request=>{const {error}=await request;assert.ok(error,"Expected access denial");};
const sessions={};
for(const role of ["owner","admin","estimator","project_manager","employee"]) {
 const s=client();await ok(s.auth.signInWithPassword({email:"qa-team-"+role+"@contractoros.test",password}));sessions[role]=s;
}
const {owner,admin,estimator,project_manager:pm,employee}=sessions;
assert.equal((await ok(owner.from("companies").select("name").eq("id",company).single())).name,"QA Browser Team");
const members=await ok(owner.from("company_members").select("id,user_id,role").eq("company_id",company));
const member=role=>members.find(m=>m.role===role);
const can=(s,p)=>ok(s.rpc("has_company_permission",{target_company_id:company,permission_name:p}));
assert.equal(await can(admin,"team.manage"),true);assert.equal(await can(admin,"settings.financial"),false);
assert.equal(await can(estimator,"team.view"),false);assert.equal(await can(employee,"reports.financial"),false);
for(const table of ["companies","estimates","estimate_items","rate_library","projects","invoices","invoice_items","payments","project_costs","audit_events"])assert.deepEqual(await ok(employee.from(table).select("*")),[]);
await denied(employee.rpc("write_audit",{target_company:company,event:"forged",entity:"project"}));
await denied(estimator.from("company_members").update({role:"owner"}).eq("id",member("estimator").id));
const customer=await ok(estimator.from("customers").insert({company_id:company,name:"QA API Customer"}).select().single());
const estimate=await ok(estimator.from("estimates").insert({company_id:company,customer_id:customer.id,estimate_number:"QA-"+Date.now(),project_name:"QA Field Project",valid_until:"2026-12-31",total:100,subtotal:100}).select().single());
await ok(estimator.from("estimate_items").insert({company_id:company,estimate_id:estimate.id,service_name:"QA service",category:"QA",description:"Private material notes",customer_description:"QA service",unit:"each",quantity:1,material_unit_cost:100}));
await ok(estimator.rpc("duplicate_estimate",{target_estimate_id:estimate.id}));
const token=await ok(estimator.rpc("send_estimate",{target_estimate_id:estimate.id}));
const anon=client();
await ok(anon.rpc("approve_public_estimate",{target_token:token,signer_name:"QA Test Only",signer_email:"qa-client@contractoros.test",signature_kind:"typed",signature_value:"QA TEST - no real work",accepted_terms:true}));
const project=await ok(owner.rpc("create_project_from_estimate",{target_estimate_id:estimate.id}));
await ok(pm.rpc("add_project_cost",{target_project_id:project,cost_date:"2026-09-07",category:"labor",description:"QA cost",vendor:"QA",amount:10}));
await ok(pm.rpc("update_project_details",{target_project:project,start_date:"2026-09-08",completion_date:"2026-09-12",internal_notes:"PRIVATE QA NOTE",crew_notes:"Arrive at 8 AM. Use the side entrance."}));
await ok(owner.rpc("assign_project_member",{target_project:project,target_user:member("employee").user_id}));
const assigned=await ok(employee.rpc("get_assigned_projects"));
assert.equal(assigned.length,1);assert.equal(assigned[0].notes,"Arrive at 8 AM. Use the side entrance.");
for(const key of ["original_contract_value","estimated_internal_cost","profit","margin","labor_rate","overhead","markup"])assert.equal(JSON.stringify(assigned).includes('"'+key+'"'),false);
const invoice=await ok(pm.rpc("create_invoice",{payload:{project_id:project,invoice_number:"QA-INV-"+Date.now(),due_date:"2026-10-07"},line_items:[{description:"QA service",quantity:1,unit_price:50,taxable:false}]}));
await ok(pm.rpc("send_invoice",{target_invoice_id:invoice}));
await denied(employee.rpc("send_invoice",{target_invoice_id:invoice}));
await ok(owner.rpc("set_member_status",{member_id:member("employee").id,new_status:"deactivated"}));
assert.deepEqual(await ok(employee.rpc("get_assigned_projects")),[]);assert.equal(await can(employee,"dashboard.view"),false);
await ok(owner.rpc("set_member_status",{member_id:member("employee").id,new_status:"active"}));
assert.equal(await can(employee,"assigned_projects.view"),true);
await denied(owner.rpc("set_member_status",{member_id:member("owner").id,new_status:"deactivated"}));
await denied(owner.rpc("change_member_role",{member_id:member("owner").id,new_role:"admin"}));
const events=await ok(owner.from("audit_events").select("user_id,event_type").eq("company_id",company));
assert.ok(events.some(e=>e.user_id===member("project_manager").user_id&&e.event_type==="project_cost_added"));
console.log(JSON.stringify({result:"PASS",checks:"5 logins; roles; REST exposure; estimator create/duplicate/send; customer approval; PM cost/invoice; assignment; deactivation/reactivation; Owner safety; audit",project,invoice}));
for(const s of Object.values(sessions))await s.auth.signOut();
